/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CallingNative */

#ifndef _Included_CallingNative
#define _Included_CallingNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CallingNative
 * Method:    nativeGetVoid
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CallingNative_nativeGetVoid
  (JNIEnv *, jobject);

/*
 * Class:     CallingNative
 * Method:    nativeGetBoolean
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_CallingNative_nativeGetBoolean
  (JNIEnv *, jobject);

/*
 * Class:     CallingNative
 * Method:    nativeGetInteger
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_CallingNative_nativeGetInteger
  (JNIEnv *, jobject);

/*
 * Class:     CallingNative
 * Method:    nativeSaveScreenshotToClipboard
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CallingNative_nativeSaveScreenshotToClipboard
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
