javac CallingNative.java
javah -jni CallingNative

gcc CallingNative.c -o CallingNative.dll -shared -m64 -fPIC -I "C:\Program Files\Java\jdk1.8.0_25\include" -I "C:\Program Files\Java\jdk1.8.0_25\include\win32"
