/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ambilight_AmbilightGdi */

#ifndef _Included_ambilight_AmbilightGdi
#define _Included_ambilight_AmbilightGdi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ambilight_AmbilightGdi
 * Method:    nativeInit
 * Signature: (II[[I)V
 */
JNIEXPORT void JNICALL Java_ambilight_AmbilightGdi_nativeInit
  (JNIEnv *, jobject, jint, jint, jobjectArray);

/*
 * Class:     ambilight_AmbilightGdi
 * Method:    nativeGetScreenSegmentsColorBytes
 * Signature: ()[[B
 */
JNIEXPORT jobjectArray JNICALL Java_ambilight_AmbilightGdi_nativeGetScreenSegmentsColorBytes
  (JNIEnv *, jobject);

/*
 * Class:     ambilight_AmbilightGdi
 * Method:    nativeSaveScreenshotToClipboard
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ambilight_AmbilightGdi_nativeSaveScreenshotToClipboard
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
